name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
  
    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Configure Terraform Cloud CLI
      run: echo -n "credentials \"app.terraform.io\" { token = \"$TF_API_TOKEN\" }" > $HOME/.terraformrc

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
